<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1168e3739a4555dfbe1c1e10d8cb7f5e
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Box\\Spout\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Box\\Spout\\' => 
        array (
            0 => __DIR__ . '/..' . '/box/spout/src/Spout',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1168e3739a4555dfbe1c1e10d8cb7f5e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1168e3739a4555dfbe1c1e10d8cb7f5e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
